Add bookings
AhraAvidzba/java-shareit pull request #2
Opened 2023-06-26 10:46 UTC by AhraAvidzba

2023-06-27 08:27 UTC, TomattmanYandex requested changes
Привет, комменты в коде

2023-06-27 08:27 UTC, TomattmanYandex commented on pom.xml
> +<!--		<dependency>-->
Не оставляем закомменченого кода, в том числе зависимостей

2023-06-27 08:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/ShareItApp.java
> +
закомменченный код не допускается

2023-06-27 08:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "_start")
почему имена столбцов начинаются с нижнего подчеркивания? и почему одни начинаются с него, другие нет
лучше убрать это нижнее подчеркивание, и дал\ть чуть более понятные имена, например не start а strat_date

2023-06-27 08:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query("select b " +
этот запрос можно сделать точно также как и остальные, чтобы он сгенерировался по имени метода

2023-06-27 08:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findByBooker_Id(Long bookerId, Sort sort);
нижние подчеркивания очень мешают чтению кода, можно обойтись и без них

2023-06-27 08:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query("select b " +
этот запрос тоже можно переделать

2023-06-27 08:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        List<BookingOutDto> bookingsOfItem = findAllBookingsOfItem(bookingDto.getItemId());
возможно проще вариант
сделать метод репозитория который вернется все букинги в промежутке времени, и тут вызвать этот метод, с датами из нового букинга, и если будет что-то найдено, значит есть пересечения по времени

2023-06-27 08:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/BookingIdOutDto.java
> +    @Future
это выходная дто зачем нам ее валидировать, ведь мы сами проставляем в нее значения

2023-06-27 08:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/BookingOutDto.java
> +    @NotNull
аналогично с другим выходным дто

2023-06-27 08:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/exceptions/IncorrectBookingDateException.java
> +public class IncorrectBookingDateException extends RuntimeException {
чем эта ошибка отличается от bookingTimeCrossing может стоит оставить только одну

2023-06-27 08:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/exceptions/IsUpToDateException.java
> +public class IsUpToDateException extends RuntimeException {
с мысл этой ошибки вообще не понятен

2023-06-27 08:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/exceptions/SameBookerAndOwnerException.java
> +public class SameBookerAndOwnerException extends RuntimeException {
а эта ошибка чем отличается от AccessRestricted

2023-06-27 08:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/exceptions/UserDontHaveBookingException.java
> +public class UserDontHaveBookingException extends RuntimeException {
может просто сделать notFoundException

2023-06-27 08:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        BookingIdOutDto lastBooking = getLastBookings(List.of(itemId), userId, targetDate).get(itemId);
1) зачем получать целую мапу, раду только одного значения, 
2) где будет использоваться с получением мапы

Кажется ты переиграл сам себя

2023-06-27 08:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        BookingIdOutDto lastBooking = getLastBookings(List.of(itemId), userId, targetDate).get(itemId);
создается лист для получения только по одному букингу, лучше сделать перегрузку метода чтобы принимал или лист или один элемент (если вообще где то надо принимать лист)

2023-06-27 08:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +//        if (sameEmailUser.isPresent()) {
но закоменченный код не допускается

2023-06-27 08:27 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/ShareItTests.java
> -package ru.practicum.shareit;
зачем коментить этот тест?

2023-06-27 09:09 UTC, AhraAvidzba commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "_start")
если задаю имена "end" "start" , бд ругается видимо потому что зарезервированные слова. Вылетает ошибка PSQLException: ERROR: syntax error at or near "end" и тд. Но поправлю на end_date

2023-06-27 11:03 UTC, AhraAvidzba commented on src/main/java/ru/practicum/shareit/exceptions/IncorrectBookingDateException.java
> +public class IncorrectBookingDateException extends RuntimeException {
по тестам в постмане эти ошибки выбрасывают разные коды, потому пришлось сделать разные исключения

2023-06-27 11:07 UTC, AhraAvidzba commented on src/main/java/ru/practicum/shareit/exceptions/UserDontHaveBookingException.java
> +public class UserDontHaveBookingException extends RuntimeException {
проблема в том, что по тестам эта ошибка должна возвращать код BAD_REQUEST (400) потому если назвать notFoundException название исключения не будет соответствовать коду возвращаемой ошибки...

2023-06-28 07:24 UTC, TomattmanYandex approved these changes
Принято

2023-06-28 07:25 UTC, merged