Add item requests
AhraAvidzba/java-shareit pull request #3
Opened 2023-07-10 18:19 UTC by AhraAvidzba

2023-07-11 08:16 UTC, TomattmanYandex requested changes
Коменты в коде, проверь однотипные ошибки во всех файлах,

2023-07-11 08:16 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                //тут в тестах постман запрашивается порядковый номер элемента а не страницы потому page = from / size
1) стоит добавить валидацию на параметр, чтобы первый был >= 0 а второй больше 0
2) в каждом вызове создается PageRequest, если вдруг поменяются требования, то прийдется это переделывать в каждом строчке, если же создать PageRequest в начале  а лучше в отдельном утильном методе, то при каких либо изменениях надо будет поменять только в одном месте

2023-07-11 08:16 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                //тут в тестах постман запрашивается порядковый номер элемента а не страницы потому page = from / size
первый пункт отменяется, увидел проверку, но можно это сделать аннотациями валидации прямо в контроллере

2023-07-11 08:16 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +
новая лишняя строчка?

2023-07-11 08:16 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +@Repository
на репозитории не обязательно вешать аннотацию Spring видит что наследуемся от JpaRepository и так понимает что это репозиторий

2023-07-11 08:16 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    ObjectMapper mapper;
модификатор лдоступа

2023-07-11 08:16 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingService bookingService;
модификатор доступа

2023-07-11 08:16 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    List<Booking> savedBookings;
модификатор доступа

2023-07-11 08:16 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplIntegrationTest.java
> +    void findAllBookingsByState() {
как то маловато тестов
а еще для наглядности тесты разделяют часто на три части 
//given 
подготовка данных
//when
вызов тестируемого метода
//then
проверка условий

эти коменты прям добавляют в тестовые методы, чтобы разбить их на части и код был нагляднее

2023-07-11 08:16 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    void saveBooking_whenItemNotFound_thenContentNotFountExceptionThrown() {
методы именуюит немного по другому
название тестируемого метода_ что должно происходить_ при каких условиях
в твоем случае, последние две части перепутаны, 

а еще слова when и then можно удалить, во первых используется обычно should и When во вторых, их заменяют нижние подчеркивания

2023-07-11 08:16 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +        Assertions.assertThrows(
очень непонятные тесты, непонятно почему должна падать ошибка, и причина основная в плохом именовании метода, лучше бы назвать
saveBooking_throwException_(А причину я сам не понял, почему тут должна упасть ошибка

2023-07-11 08:16 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +                () -> bookingService.saveBooking(bookingInDto));
так почему она тут падает

2023-07-11 15:44 UTC, AhraAvidzba commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    void saveBooking_whenItemNotFound_thenContentNotFountExceptionThrown() {
Привет, в теории нас учили по другому. В уроке от ЯП "Mock-тестирование" (по ссылке ниже в видео с 17:54). Там рекомендуют названия тестовым методам давать такое "имя тестируемого метода"_"условие приводящее к возникновению нашего кейса"_"ожидаемый в итоге резултьтат"

Ссылка на видео [https://disk.yandex.ru/d/ytutjO9V6qZiFw/15%20%D1%81%D0%BF%D1%80%D0%B8%D0%BD%D1%82/15.%20Mock-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5.%20%D0%93%D0%BB%D0%B5%D0%B1%20%D0%A8%D0%B8%D1%88%D0%BA%D0%BE%D0%B2/%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D1%8C%20%D0%B2%D0%B5%D0%B1%D0%B8%D0%BD%D0%B0%D1%80%D0%B0%2016.%20Mock-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5.%20%D0%93%D0%BB%D0%B5%D0%B1%20%D0%A8%D0%B8%D1%88%D0%BA%D0%BE%D0%B2.mov]

2023-07-11 15:52 UTC, AhraAvidzba commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +        Assertions.assertThrows(
Условие приводящее к возникновению ошибке описывается после первого нижнего подчеркивания. В моем случае метод называется "saveBooking_whenItemNotFound_thenContentNotFountExceptionThrown" из него следует, что исключение выбрасывается, когда не найдет айтем букинг которого мы пытаемся сохранить.
Для лучшего понимания добавил отдельные переменные с говорящими названиями, которые передаются в аргументы тестируемого метода.

2023-07-11 15:53 UTC, AhraAvidzba commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +                () -> bookingService.saveBooking(bookingInDto));
см. коммент выше

2023-07-12 09:54 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void saveBooking_whenBookingIsNotValid_thenMethodArgumentNotValidExceptionThrown() {
хочется добавить, что иногда стоит добавить в название метода, чем обьект не валдиен

2023-07-12 09:54 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    void saveBooking_whenItemNotFound_thenContentNotFountExceptionThrown() {
без проблем, это просто разные подходы именования методов, я топлю за тот который мне нравится использовать, и удобно читать)))
поясню за свой вариант - в некоторых тестах часть про условие является избыточной, (например, когда мы тестируем успешное выполнение при нормальных условиях) и тогда эту часть можно опустить,и в случае если условие на последней позиции, то порядок не изменяется,
на первой позиции всегда навзание метода, 
на второй что должно произойти
на третьей при каких условиях (если мы ее не добавим , то первые две позиции останутся без изменений)
а если сначала писать условие, потом что должно произойти, то, либо мы всегда пишем условие, чтобы не путаться, либо путаемся

2023-07-12 09:58 UTC, TomattmanYandex approved these changes
Aceptado (Принято(Исп))

2023-07-12 09:58 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +        Assertions.assertThrows(
отлично, запутало Item в имени, часто item можно назвать любой объект, эли элемент по которому итерируем

2023-07-12 09:58 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +        Assertions.assertThrows(
говорящие название переменных, это очень хорошо, все становится в разы понятнее

2023-07-12 15:49 UTC, merged